// Code generated by himesan; DO NOT EDIT.
// himesan:compiler 0.1.0-dev
// himesan:runtime-abi sando.v1
// himesan:source-sha256 f4ba01010ed5f5ba1e979702d82e95312bc0a4b13cc205c098926839be4ecb73

package golden

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABI

func Greeting(name string) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/compiler/testdata/golden/basic.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/compiler/testdata/golden/basic.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<p class=\"greeting\">Hello, "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/compiler/testdata/golden/basic.sando:7:32
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (name)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/compiler/testdata/golden/basic.sando:7:39
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, ".</p>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
