// Code generated by himesan; DO NOT EDIT.
// himesan:compiler 0.1.0-dev
// himesan:runtime-abi sando.v1
// himesan:source-sha256 696c391538cdc50c5ab1abea23b561fa354e56eaf73b7ad6aabe130389715a8c

package views

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABI

func Home(view HomeView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line views/home.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line views/home.sando:6:37
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<section aria-labelledby=\"home-heading\">\n  <h1 id=\"home-heading\">"); __himesan_error != nil {
			return __himesan_error
		}
//line views/home.sando:8:29
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Heading)); __himesan_error != nil {
			return __himesan_error
		}
//line views/home.sando:8:44
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</h1>\n  <p>"); __himesan_error != nil {
			return __himesan_error
		}
//line views/home.sando:9:10
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Intro)); __himesan_error != nil {
			return __himesan_error
		}
//line views/home.sando:9:23
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line views/home.sando:10:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (BrowseResults(view.Browse))); __himesan_error != nil {
			return __himesan_error
		}
//line views/home.sando:10:36
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n</section>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
