// Code generated by himesan; DO NOT EDIT.
// himesan:compiler 0.1.0-dev
// himesan:runtime-abi sando.v1
// himesan:source-sha256 c9a8102588cb94f946a36414291d12cb681e605acc93c2b5dc8d74fd33ae5603

package views

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABI

func Layout(view LayoutView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line views/layout.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line views/layout.sando:6:37
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>"); __himesan_error != nil {
			return __himesan_error
		}
//line views/layout.sando:12:14
		if __himesan_error := __himesan_sando.WriteRCDATA(__himesan_writer, (view.Title)); __himesan_error != nil {
			return __himesan_error
		}
//line views/layout.sando:12:27
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, " · "); __himesan_error != nil {
			return __himesan_error
		}
//line views/layout.sando:12:35
		if __himesan_error := __himesan_sando.WriteRCDATA(__himesan_writer, (view.SiteName)); __himesan_error != nil {
			return __himesan_error
		}
//line views/layout.sando:12:51
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</title>\n</head>\n<body>\n  <a href=\"#main\">Skip to content</a>\n  <header><a href=\"/\">"); __himesan_error != nil {
			return __himesan_error
		}
//line views/layout.sando:16:27
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.SiteName)); __himesan_error != nil {
			return __himesan_error
		}
//line views/layout.sando:16:43
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</a></header>\n  <main id=\"main\">"); __himesan_error != nil {
			return __himesan_error
		}
//line views/layout.sando:17:23
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (view.Body)); __himesan_error != nil {
			return __himesan_error
		}
//line views/layout.sando:17:35
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</main>\n  <footer>Built with Sandwich Hime.</footer>\n</body>\n</html>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
