// Code generated by himesan; DO NOT EDIT.
// himesan:compiler 0.1.0-dev
// himesan:runtime-abi sando.v1
// himesan:source-sha256 8d59b45799d0ed2e9e6997f286315f2cb794ea660940978ec39efa3b9a3b94ab

package views

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABI

func SecurityProbe(url string, title string, text string) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line views/security_probe.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line views/security_probe.sando:6:37
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<a href=\""); __himesan_error != nil {
			return __himesan_error
		}
//line views/security_probe.sando:7:14
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (url)); __himesan_error != nil {
			return __himesan_error
		}
//line views/security_probe.sando:7:20
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" title=\""); __himesan_error != nil {
			return __himesan_error
		}
//line views/security_probe.sando:7:33
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (title)); __himesan_error != nil {
			return __himesan_error
		}
//line views/security_probe.sando:7:41
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">"); __himesan_error != nil {
			return __himesan_error
		}
//line views/security_probe.sando:7:47
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (text)); __himesan_error != nil {
			return __himesan_error
		}
//line views/security_probe.sando:7:54
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</a>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
